language: java

jdk:
  - openjdk14

sudo: false

env:

  global:

    CODECOV_TOKEN="c05410c9-6061-474c-ae9a-e2e0fcd6d0d2"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - Mishail.avram@mail.ru
    on_success: never # default: change
    on_failure: always # default: always